from setuptools import find_packages, setup

setup(
    name="city_metrix",
    version="0.3.0",
    description="Module to calculate various metrics on cities.",
    packages=find_packages(),
    author="Justin Terry, Kenn Cartier",
    license="MIT",
    install_requires=[
        "numpy",
        "geopandas",
        "shapely",
        "xarray==2025.3.1",
        "pytest",
        "timeout-decorator",
        "geocube",
        "pandas",
        "earthengine-api",
        "scikit-image>=0.25.2",
        "pyproj",
        "setuptools",
        "requests",
        "cdsapi",
        "geemap>=0.35.3",
        "scipy",
        "osmnx==2.0.2",
        "pytz",
        "timezonefinder",
        "exactextract>=0.2.0",
        "rasterio",
        "boto3",
        "rioxarray",
        "dask[complete]<=2025.2.0",
        "utm",
        "gdal",
        "odc-stac",
        "pystac-client",
        "xarray-spatial",
        "xee",
        "matplotlib",
        "jupyterlab",
        "s3fs",
        "pip",
        "cfgrib",
        "overturemaps",
        "ipython"
    ],
    package_data={
        'city_metrix': ['ut_globus_city_handler/global_ut_globus_cities.gpkg']
    },
)
